CREATE TABLE t5 (
    codi INTEGER PRIMARY KEY AUTO_INCREMENT,
    model VARCHAR(20) NOT NULL,
    marca VARCHAR(20) NOT NULL,
    matricula VARCHAR(20) UNIQUE NOT NULL,
    bastidor VARCHAR(30) UNIQUE NOT NULL,
    color VARCHAR(30)
);
